### ISSUE TITLE
Triển khai thiết kế khu vực trò chuyện chính

### ISSUE THREAD

**Issue by minh-pionero** [minh-pionero/demo#1]
- Per-message type
	- Reference ShowMessage200ResponseMessageAllOfDataInner
	- The following display is notated according to this type
- [ ] Message sent date display
	- [ ] Ignore msg_type 11 and 12 as they are dedicated to smartphone apps
	- [ ] Do not display deleted system messages
	- [ ] Edited items have an edit icon
- [ ] message
	- See createChatMessageHTML in resources/js/chat/chat_pc/chat_common_pc.js for rendering implementation
	- [ ] Ignore msg_type 11 and 12 as they are dedicated to smartphone apps
	- [ ] Do not display deleted system messages
	- [x] Right for me, left for others, center for system messages
	- [x] No icons for my messages
  	- [ ] background color
  		- Other than system messages, background colors are usually applied like blocks and cards.
  		- [x] mine is background color primary.light
  		- [x] Others are basic, standard background color background.default
  		- [ ] secondary.light when the other contains a mention of me
  	- [ ] Others basically have the name and icon of the user who sent them.
	- [ ] When msg_type is TASK_NOTICE (6) or COMPLETION (7)
		- userIconUrl uses AccountCircle
			- The existing one is delivered at `/img/user000.png`
		- no username part
	- [ ] If there is a task_name when it is not TASK_NOTICE or COMPLETION
		- System message display for tasks
			- `<a>${task_name}</a>のコメント欄にて、${ isMyMsg ? 'あなたが' : `${userName}さんがあなた宛に` }コメントしました。`
	- [x] Display message as system message when msg_type is MEMBER_JOIN (4), INVITATION (5), GUEST_JOIN (9), LEAVE (10)
		- Since messageInfo.actionUser is given to data-actionUser, this is the confirmation key for system message deletion
	- [ ] When msg_type is REQUEST_APPLY (8), approval request message for master authority, system message for others
		- This system message does not have a data-actionUser, so it is not subject to deletion.
		- Approval request messages are treated as other
			- userIcon uses AccountCircle
			- no username part
			- Display contents change according to the state of guestInfo.status
				- 0 Approve/Reject button
				- 1 approval message
				- 2 rejection message
				- 3 no indication about
	- [ ] If reply_info is attached, add reply destination information etc.
		-Described with a reply icon (turnright) to indicate who the user is replying to
			- My reply to my message `I replied to myself`
			- Others reply to my message `${userName} replied to me`
			- Your reply to someone else's message `You replied to ${replay_info.from_name}`
			- Reply to someone else's message `${userName} replied to ${replay_info.from_name}`
		- Reply-to message display
			- If del_flag is set, all are treated as msg_type TEXT(0) `message canceled` display
			- Image display for stamp
			- The text is displayed in one line by applying decorations and removing the line break element ` br `
				- fixed display width
				- Omitted with a three-point leader
				- Refer to msg_type TEXT section for details such as decoration.
			- Show attachments if any
				- Reduced display if the attached file type is image4
				- File icon display otherwise
			- Click to go to reply-to message
		- Need to adjust the message display part
	- [ ] If there is a message_quote, display it as quoted source information along with quote_info
		- Source information
			-`quote: ${quote_info.from_name}`
			- See the section on TEXT for the display of message_quote.
			- See the section on TEXT for the display of message_quote.
			- Fixed width If one line is more than the width, do not wrap and omit with a three-point leader for each line
		- Need to adjust the message display part
	- [ ] if msg_type is TEXT(0)
		- [ ] If there is a decorative character, change it → It has been handled by the implementation of #10 etc.
			- For details, refer to css specification of deco_in members public/css/chat/chat_deco_selection.css
			- [title]~[/title]
				- 左側に4pxのボーダー（primary.main）+bold
			- [info]~[/info]
				- ブロック全周を1pxのボーダー（grey.400）
			- [hr]
				- 下部1pxボーダー（grey.400）
			- [bold]~[/bold]
				- bold
			- [red]~[/red]
				- color red（secondary.dark）
		- [ ] If url is included, link target='_blank' rel='noopener' → Corresponded by implementation of #10 etc.
			- url regular expression: `/((h?)(ttps?://[-_.!
*'()a-zA-Z0-9;''/?:@&=+ $,%#[…]u3001-u30FEu4E00-u9FA0uFF01-uFFE3]+))/g`
			- no underline
		- [ ] If an email address is included, link to mailto target='_blank' rel='noopener' → #10 has been implemented etc.
			- Email address regular expression: `/(/|:)?([a-zA-Z0-9])+([a-zA-Z0-9._-])*@([a-zA-Z0 -9_-])+([a-zA-Z0-9._-]+)+/g`
			- no underline
		- [ ] If there is a @ in the mention, make it a link → Already handled by implementation of #10 etc.
			- Link to `#`
			- no underline
			- Match with chat room member information
				- username in joinedusers contains spaces between gender names but not in mentions
			- `@AI` and `@all` do not match
		- [ ] if fileCount is greater than 0
			- [ ]Attachment display → Supported by implementation of #10 etc.
			- message individually
			- Change display with file.type
				- 4 Display image preview in IMAGE
				- 1 (TEXT), 2 (PDF), 4 (IMAGE), and 8 (MOVIE) support preview, so click to preview modal display
					- If the movie exceeds 40mb, a download link will be given
					- Preview modal display on click → Preview modal itself is being implemented in #27
				- Otherwise download link provided
				- The display format is common except for images
	- [ ] if msg_type is ATTACHMENT(2)
		- if filecount is greater than 0
			- Attachment display
			- message individually
	- [ ] If msg_type is STAMP(1)
		- Stamp image display
		- Display switching for each stamp_no
			- Display what is distributed on the members side
			- 1 'img/common/thumbs-up-solid_eg.png'
			- 2 'img/common/chat-stamp1.png'
			- 3 'img/common/chat-stamp2.png
			- 4 'img/common/chat-stamp3.png'
	- [ ] If msg_type is TASK_NOTICE(6)
		- Display messages, task names, and due dates in a dedicated format
		- Task name is a link to the task (`tasks/detail/${task_id}`) if not deleted
	- [ ] if msg_type is COMPLETION(7)
		- Show completion report
		- Get and display the number of executions
	- [ ] If msg_type is AI(13)
		- Loading display because ai is waiting for an answer
		- msg_type becomes 0 when answer is possible
- [ ] reaction display
	- [ ] Individual display for each reaction
	- The image path to be displayed for each reaction_no is determined
	- Display what is distributed on the members side
		- 1: 'img/common/chat-reaction-hart.png'
		- 2: 'img/common/chat-reaction-glad.png'
		- 3: 'img/common/chat-reaction-shock.png'
		- 4: 'img/common/chat-reaction-cry.png'
		- 5: 'img/common/chat-reaction-angry.png' Display may be necessary, but cannot be added
		- 6: 'img/common/chat-reaction-thumbs-up.png'
		- 7: 'img/common/chat-reaction-understand.png'
		- 8: 'img/common/chat-reaction-bow.png'
		- 9: 'img/common/chat-reaction-congrats.png'
	- [ ] Reaction performer's name display on each reaction hover
	- [ ] If there are multiple people, display `other ○ names` except for one
	- [ ] Reaction list modal display on reaction click
	- Go to implementation in #39
- [ ] message action menu
	- [x] Display on hover to message area
	- [ ] Does not appear in system messages, notifications, approval requests, task information, or deletion messages
	- [ ] different from others
		- from left to right
		- [ ] myself
			- context menu
				- Click to view additional
				- コピー(Copy)
					- Sao chép vào clipboard
					- Not displayed in files and stamps
				- 削除 (Delete)
					- メッセージ削除 (xóa tin nhắn)
			- edit icon
				- Thêm hiển thị chỉnh sửa vào tin nhắn
				- Chuyển thông tin chỉnh sửa đến vùng nhập liệu
			- reaction icon
				- Reaction selection modal display on click
				- [ ] reaction selection modal
					- Display name in tooltip on each icon hover
					- display from left
						- ハート、喜ぶ、驚く、悲しむ、いいね、了解、お辞儀、おめでとう
						- 1、2、3、4、6、7、8、9
						- 5 is not displayed
					- See resources/views/chat/chat_pc/reaction_dialog.blade.php in members
			- reply icon
				- Pass the reply information to the input area
			- bookmark icon
				- Always display when bookmarked
				- Nhấp để chuyển trạng thái dấu trang
				- don't show on stamp
		- [ ] người khác
			- bookmark icon
				- don't show on stamp
			- reaction icon
			- reply icon
			- copy icon
				- Copy to clipboard
				- Not displayed in files and stamps
- [ ] message hover menu
	- [ ] Displayed by hovering over the message display area
	- [ ] Sent date and last edit if any
	- [ ] Not visible in system messages
	- [ ] The display position is fixed at the bottom of the message
	- [ ] It does not have to be displayed if it is cut off
	- [ ] Do not hide the input area or header
- [ ] read icon
	- [ ] Check read icon for each message
	- [ ] Up to 5 or more will display `〇〇 +`
	- [ ] Toolchip display of read information on hover
- [ ] Read position display
	- `unread message` in the center of secondary.dark divider
- Message quote modal display when selecting text in the text message display area by dragging → Implement in #41
	- Pass quoted message information to the input area
- [ ] loading screen
	- circular progress
	- https://mui.com/material-ui/react-progress/#circular-indeterminate
	- https://mui.com/material-ui/api/circular-progress/
	- https://xd.adobe.com/view/74a7b0c1-c128-46fe-b7aa-4e8dc6f7dba6-21f4/screen/6802366d-ed4e-4df5-a5d3-005686f9e312/specs/
- with scroll
	- I want to use simplebar-react
	- Implement and reuse as a common component
